pub mod batch_query;
pub mod benchmark_gate;
pub mod caveat_contract;
pub mod cli;
pub mod commands;
pub mod completions;
pub mod config_facts;
pub mod diff_proof;
pub mod generation_manifest;
pub mod index;
mod index_status;
pub mod install;
pub mod java_provider;
pub mod lancedb_store;
pub mod lsp;
pub mod output;
mod path_compat;
pub mod project_graph;
pub mod provider_help;
pub mod query_input;
pub mod remote;
pub mod routes;
pub mod rust_provider;
pub mod saved_query;
pub mod scan_diagnostics;
pub mod scip;
pub mod scip_index;
pub mod scip_indexer;
pub mod scip_proto;
pub mod scip_provider;
pub mod search;
pub mod search_pattern;
pub mod semantic_facts;
pub mod semantic_provider;
pub mod snapshot_store;
pub mod syntax;
pub mod text_index;
pub mod ts_provider;
pub mod watcher;
pub mod workspace;

pub mod go_provider;
pub mod graph;
pub mod mcp;
pub mod query;
pub type AppResult<T> = anyhow::Result<T>;
