/// Generated SCIP protobuf types.
/// The actual types are generated by prost-build from proto/scip.proto
/// into the OUT_DIR, and included here.
pub mod proto {
    #![allow(clippy::all, non_snake_case, unused_qualifications)]
    include!(concat!(env!("OUT_DIR"), "/scip.rs"));
}
